### ISSUE TITLE
Unable to upload files with special chars in its names

### ISSUE THREAD

**Issue by ghost** [ePaul/jsch-documentation#3]
sftpChannel.put("test.txt", "test.txt"); // OK
sftpChannel.put("tes t.txt", "test.txt"); // OK
sftpChannel.put("tes t.txt", "tes t.txt"); // Caused by: 3: Permission denied
sftpChannel.put("tes t.txt", "tes-t.txt"); // Caused by: 3: Permission denied

**Comment by ePaul** [comment]
Hi,

sorry for answering only this late.

In this project, I don't handle the actual functionality of the JSch library, but I am just adding javadoc documentation to it. For problems with Jsch, please use the contact points mentioned at the [official website](http://www.jcraft.com/jsch/). (I think the best point would be the mailing list.)

I'm closing this issue now.
