### ISSUE TITLE
ChannelSftp.stat and lstat work the other way around

### ISSUE THREAD

**Issue by robtimus** [ePaul/jsch-documentation#4]
According to the current documentation, stat does not follow links and lstat does. According to [section 8.5 of draft-ietf-secsh-filexfer-13](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-13#section-8.5) this should be the other way around:

> SSH_FXP_STAT and SSH_FXP_LSTAT only differ in that SSH_FXP_STAT follows symbolic links on the server, whereas SSH_FXP_LSTAT does not follow symbolic links.

This is an error in the JSch documentation, because stat and lstat behave the way they should.

**Comment by ePaul** [comment]
Good catch, thanks. I suppose that was a simple mistake by me when adding the documentation (or version 0.1.44 behaved differently, which I don't believe).

I'll first have to set up my build system here to verify this, but feel free to open a pull request until I get to do so.

**Comment by robtimus** [comment]
I've changed both the JavaDoc in the source files (on master) and the HTML files in the generated API files (on gh-pages). There's a pull request for both branches.

**Comment by ePaul** [comment]
Thanks, both are merged.
