### ISSUE TITLE
Terminal emulation support feature

### ISSUE THREAD

**Issue by ThanasisBarekas** [ePaul/jsch-documentation#9]
Hello,

In readme file it is stated that the project is interested in implementing terminal emulation.
Is there any timeline for this ? 

Thank you,
Thanasis

**Comment by ePaul** [comment]
Hi, thanks for your interest.

Please note that the goal of this repository is just to add javadoc to the actual [JSch project](http://www.jcraft.com/jsch/).
I copied that project's code and README (last time in 2015, for 0.1.54) and added the Javadoc to it. I'm not actively maintaining the documentation, and even less the actual code.

Please check out that [project's website](http://www.jcraft.com/jsch/) for more information on their goals and timelines. There is also a mailing list where you can ask. (The page mentions a program called [JCTerm](http://www.jcraft.com/jcterm/), which is a terminal emulator in Java.)
